services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ADMIN_USERNAME
      KEYCLOAK_ADMIN_PASSWORD: ADMIN_PASSWORD
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://SQL_HOST:PORT;databaseName=DATABASE_NAME;trustServerCertificate=true
      KC_DB_USERNAME: SQL_USER
      KC_DB_PASSWORD: SQL_USER_PASSWORD
      KC_DB_TX_TYPE: enabled
      KC_DB_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
    command: start-dev --transaction-xa-enabled=false
    volumes:
      - ./themes/.:/opt/keycloak/themes/.
      - ./providers/.:/opt/keycloak/providers/.
networks:
  keycloak-network:
    driver: bridge
      